---
# Populated at runtime by terraform_inventory role; static fallback for testing
all:
  children:
    sap_mod:
      children:
        sap_builders:
          hosts: {}
        sap_db2:
          hosts: {}
        sap_app:
          hosts: {}
