---
# Dynamic builder host is added at runtime by golden_image role
all:
  children:
    localhost:
      hosts:
        localhost:
          ansible_connection: local
    sap_builders:
      hosts: {}
    sap_workloads:
      hosts: {}
